### ISSUE TITLE
有一个用户给我点星，我不能给他点

### ISSUE THREAD

**Issue by BarryYBL** [giswangsj/GitHubStar#1]
有一个用户给我点星，我不能给他点；我只要点进去他的项目页面 Gitstar就自动退出
## 
![image](https://user-images.githubusercontent.com/46100874/89250914-65ac4700-d648-11ea-8dad-24bffe31baf7.png)

**Comment by giswangsj** [comment]
你好，这个用户我这边是没有问题的，你知道你还有问题没
![image](https://user-images.githubusercontent.com/11539365/89723839-09716a80-da2e-11ea-9a89-e92d64f44aad.png)

**Comment by BarryYBL** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好，还是一样的，能够把这个用户的数据从我这里删除记录呢
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Barry
                            
                    
                        
                            
                                    
                                    2652612315@qq.com
                                    
                                    
                                    
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年08月9日 10:50，wangsj<notifications@github.com> 写道： 




你好，这个用户我这边是没有问题的，你知道你还有问题没





—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by giswangsj** [comment]
我看你在github上已经给他回过了，这条数据的状态也已经改成已回赞状态。

**Comment by BarryYBL** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，感谢！
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Barry
                            
                    
                        
                            
                                    
                                    2652612315@qq.com
                                    
                                    
                                    
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年08月10日 10:17，wangsj<notifications@github.com> 写道： 




我看你在github上已经给他回过了，这条数据的状态也已经改成已回赞状态。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
