### ISSUE TITLE
fork失败

### ISSUE THREAD

**Issue by raos1105** [giswangsj/GitHubStar#12]
别人可以fork我的，fork别人的时候，提示没有开启fork。但界面上我的fork是开启的，虽然没有缴费。

**Comment by raos1105** [comment]
我是比较早的用户，看下怎么弄，现在欠别人fork了

**Comment by raos1105** [comment]
现在想关fork都关不了了，点击switch就跳转到新标签

**Comment by giswangsj** [comment]
你的账号是多少？我给你处理一下吧

**Comment by giswangsj** [comment]
raos1105这个账号对吧，已经给你处理好了
