### ISSUE TITLE
增加展示开关

### ISSUE THREAD

**Issue by raos1105** [giswangsj/GitHubStar#6]
能否增加一个展示或隐藏仓库的开关按钮？因为如果这个仓库不想维护了或者暂时不想参与活动了，需要及时关闭，否则就会造成失信以及产生垃圾仓库

**Comment by ShingZhanho** [comment]
你看看我的issue #7 怎么样？

**Comment by giswangsj** [comment]
在右侧的个人信息中的第一个开关是控制隐藏仓库的
