### ISSUE TITLE
Star、Fork、Watch增加独立开关

### ISSUE THREAD

**Issue by ShingZhanho** [giswangsj/GitHubStar#7]
建议给star、fork和watch动作增加独立的开关，有时候一个repo只想要star，但是fork和watch没法另外关闭，为了不被标记为失信不得不还fork和watch。

建议做法：
增加独立开关，如果其他人做一些已经关闭的动作，就提示对方不想要这个动作所以他可以不还。

**Comment by giswangsj** [comment]
目前判断失信是以star为准，fork和watch可以暂时不管。后面会增加独立的开关。

**Comment by giswangsj** [comment]
已增加独立开关，star开关控制是否可以star以及整个仓库是否可见。watch和fork开关关闭后别人给你点赞时看不到对应的按钮
